---
# 所有模組皆可存取的共用參數
shared:
    shared_key: shared_val

# 使用的模組及其參數，可以是內建的模組或是自製模組的路徑
# 內建模組列表：https://gitlab.com/JacobLinCool/bahamut-automation/-/blob/main/src/modules/README.md
modules:
    # 註冊一些通用函式到 shared
    utils:
    report:
    ad_handler:

    # 主要功能模組
    login:
        username: your_username
        password: your_password
    sign:
    guild:
    answer:
    lottery:
        max_attempts: 20
    logout:

    # 以下是寄報告的部分
    telegram:
        channel: telegram_channel_id
    discord:
        webhook: discord_webhook_url
    line_notify:
        token: line_token
    issue:

    # 自製模組（範例）
    # /path/to/module:
    #     param1: value1
    #     param2: value2

# 瀏覽器的設定
browser:
    type: firefox
    headless: true
    firefoxUserPrefs:
        dom.webaudio.enabled: false
        media.volume_scale: 0
        media.default_volume: 0
    # executablePath: /path/to/browser

    # 更多設定請查閱：https://playwright.dev/docs/api/class-browsertype#browser-type-launch
